version: '3.8'

services:
  # MongoDB Database (Production)
  mongo:
    image: mongo:6.0
    container_name: fullsco_mongo_prod
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-fullsco_db}
    volumes:
      - mongo_data:/data/db
    networks:
      - fullsco_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (Production)
  backend:
    build: .
    container_name: fullsco_backend_prod
    environment:
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongo:27017/}
      MONGODB_DB: ${MONGODB_DB:-fullsco_db}
      PORT: ${PORT:-5000}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - fullsco_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: fullsco_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - fullsco_network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  fullsco_network:
    driver: bridge 